### ISSUE TITLE
Syncing drafts

### ISSUE THREAD

**Issue by drallgood** [benbalter/wordpress-github-sync#52]
Right now, this plugin ignores drafts.

I think it might be a good idea, to also sync drafts.

**Comment by mAAdhaTTah** [comment]
:+1: Definitely something I want to add, along with #6. Those will probably go together.

**Comment by drallgood** [comment]
Awesome :+1:

**Comment by benbalter** [comment]
How would you mark that the file is a draft  on the git side? In the Jekyll world, there are two options:

1. a `_drafts` folder, treated just like the `_posts` folder, which I'm not a big fan of because publishing means you often lose history.

2. `published: false` in the YAML front matter (which I think has greater applicability outside of Jekyll).

**Comment by drallgood** [comment]
As a Jekyll user, I'd say 1) because that's the default, but 2) seems to be easier/better for everyone.
Most people outside of the Jekyll camp might not understand, that they have to move files to publish them

**Comment by benbalter** [comment]
> As a Jekyll user

FWIW, the `published: false` pattern works with Jekyll as well.

**Comment by mAAdhaTTah** [comment]
My first inclination was 1, but we could actually do both if we wanted. I also want to mention that exporting drafts should be toggle-able in case the user doesn't want their works-in-progress made public.

**Comment by mAAdhaTTah** [comment]
Btw, now that we're using the Git Data API, I *think* we won't the history if we move the file from `_drafts` to `_posts`, so that shouldn't be an issue.

**Comment by benbalter** [comment]
> I think we won't the history if we move the file from _drafts to _posts, so that shouldn't be an issue.

Within Git, yes, but if you look at a file's history by path (e.g., on GitHub) you lose the previous edits, IIRC.

**Comment by mAAdhaTTah** [comment]
No, git will [track the rename](https://github.com/mAAdhaTTah/writing/commit/9e00378e6f8c6e71b5ddcca967fef3435afa55ec).

**Comment by mAAdhaTTah** [comment]
This actually might be a GitHub bug; the [file doesn't see all of its history on GitHub](https://github.com/mAAdhaTTah/writing/commits/master/_posts/2015-01-05-your-design-choices-political.md), but a [local git install does](https://www.evernote.com/shard/s89/sh/ae579a70-6171-4912-921f-36851e05b27c/fa43dcfc080d71539991cc85741d3681).

**Comment by mAAdhaTTah** [comment]
Reopening because it doesn't quite track the [rename](https://github.com/mAAdhaTTah/writing/commit/568fca3cdf46f212f3ec1ebbe4720b7233efdf82). Sometimes it does, if the changes are minimal, but there's a bunch of changes in the file here and git isn't tracking the rename. I just want to reask what we think about the `_drafts` folder vs. just the `published:false` part.

The other issue is the dates aren't even really going to be consistent for draft post -> published post, so the filename will change daily until the post is published. For longer posts, this may not be an issue, as the file content will match more closely than this short post will, but I do just want to bring it up for discussion, as I'm not entirely sure how people will want to export their drafts.

FWIW, I need to make some customizations based on the way I use my site, but did make me think some changes may need to be made to our current implementation.

**Comment by mAAdhaTTah** [comment]
Closing, as this is implemented. If people start using this and have issues, we can revisit this.
