### ISSUE TITLE
Ability to add subfolders based on taxonomony or category of (custom) post?

### ISSUE THREAD

**Issue by BoweFrankema** [benbalter/wordpress-github-sync#76]
I was wondering if it would be possible to automatically put published posts into a subfolder based on a category or taxonomy? So for example:

    _posts / category_name / my_post.md

This would make it easier to keep things a lot more organised :-)

**Comment by mAAdhaTTah** [comment]
There are [some filters](https://github.com/benbalter/wordpress-github-sync/blob/master/lib/post.php#L195-L213) you can hook into in order to customize the directory your posts get exported to. There is some additional information about the available hooks in the [wiki](https://github.com/benbalter/wordpress-github-sync/wiki/Customizing-WordPress----GitHub-Sync). If that's missing anything, feel free to update it.

Let me know if you have any questions about how that works.

**Comment by mAAdhaTTah** [comment]
I'm marking this as closed, since this is already a feature. If you need any help, feel free to reopen.

**Comment by ibenot** [comment]
Hi,
I'm trying to add custom meta with folder to organize my .md files following BoweFrankema code : 
`_myObj / myFolder / myfile.md`

I added my code in github_directory function (wpghs_directory_published) and it's working when I create a post from Wordpress to Github. But it seems to be broken from Github to Wordpress, the sync of my meta are broken. Is there another filters to import from Github to Wordpress ? 

Thank you very much

**Comment by mAAdhaTTah** [comment]
Yes. See https://github.com/mAAdhaTTah/wordpress-github-sync/blob/master/lib/database.php#L180 and the discussion here: https://github.com/mAAdhaTTah/wordpress-github-sync/issues/136
